### ISSUE TITLE
Plan for the migration to PHPCS 3

### ISSUE THREAD

**Issue by stof** [djoos/Symfony-coding-standard#80] opened 2017-05-31 09:45 UTC
PHPCS 3 was just released, with BC breaks for custom sniffs. what are the plans to migrate to it ?

**Comment by Telematica** [comment] 2017-05-31 23:29
@stof +1 (y).
Had to downgrade PHPCS 3 to 2.9.x to get Symfony2 CS working properly. 
Any plans to port/migrate to PHPCS 3?

**Comment by KacerCZ** [comment] 2017-06-01 05:20
Migration is in the works - see https://github.com/djoos/Symfony2-coding-standard/issues/64 and https://github.com/djoos/Symfony2-coding-standard/pull/63

**Comment by wickedOne** [comment] 2017-06-02 07:47
the current master branch is phpcs3 compatible while a 2.x branch has been created for the continuos support of phpcs2.

i'm unaware of the release strategy of @djoos, but for now i think it's easiest to lock to 188891742c6a4538831b8d0638bcc2e92fbfbfb1 which is the current 2.x branch made phpcs3 compatible so should behave exactly the same.

in the master branch there have been some additional changes like [changing the standard's name](https://github.com/djoos/Symfony2-coding-standard/issues/65) and the addition of 7 new sniffs (3 still open in pr) in an attempt to comply with symfony's current standards as described in #66, #68 and #69.

as those new sniffs are only tested on my own repositories and the past has shown there are plenty of (edge) cases resulting in false positives, those might need some additional testing and finetuning.

**Comment by djoos** [comment] 2017-06-07 09:20
v3.0.0 of the CS is in the works and will get tagged as soon as we're ready. For now PHPCS3-users should be able to make use of the master of this repo, but it's still a WIP. Comments and remarks always welcome via separate issues/PRs!

I don't think we'll backport any of the new sniffs into the 2.x branch though, however I'm open for a discussion on that.

Hope this helps!

**Comment by KIPdeKIP** [comment] 2017-06-13 15:00
From what I can tell, https://github.com/djoos/Symfony-coding-standard/pull/70 fixed a regression from upgrading to PHPCS 3.

So, should I be using b097f90fe79ec69873a0b2257ec6046137e97c3b rather than ~188891742c6a4538831b8d0638bcc2e92fbfbfb1~ to keep the same behavior after upgrading?

**Comment by djoos** [comment] 2017-06-13 15:25
@KIPdeKIP: I'd stick to the latest master until we properly release 3.0.0. Hope this helps!

**Comment by wickedOne** [comment] 2017-06-13 17:56
@KIPdeKIP indeed 188891742c6a4538831b8d0638bcc2e92fbfbfb1 has some regressions due to unexpected behaviour of phpcs3 (not sure whether it's a bug or intended behaviour) which is very unfortunate...

so to mimic the exact behaviour of the v2 branch with phpcs v3  you need to patch 188891742c6a4538831b8d0638bcc2e92fbfbfb1 and cherry pick it with b097f90fe79ec69873a0b2257ec6046137e97c3b and 8d5d452819bca3090303022bc4f780b5a8cc5c8d

@djoos it might be an idea to do the above in a seperate branch and tag it so people can stick to that until the 3.0.0 release? meanwhile i'll open an issue and investigate why the unittests stopped working (which would have prevented this from happening)

**Comment by KIPdeKIP** [comment] 2017-06-14 08:55
Instead of ~8d5d452819bca3090303022bc4f780b5a8cc5c8d~ did you mean cf5a004481beff67f199ca3c5dac209b46b81acd? ~8d5d452819bca3090303022bc4f780b5a8cc5c8d~ is giving me a "fatal: bad object" error. Did the history get rewritten at some point?

What I ended up doing is rebase picking b097f90fe79ec69873a0b2257ec6046137e97c3b and cf5a004481beff67f199ca3c5dac209b46b81acd. Dropping everything else after 188891742c6a4538831b8d0638bcc2e92fbfbfb1.

Fixed the conflicts caused by the rename from Symfony2 to Symfony and pushed them to my fork. [Does this look correct?](https://github.com/KIPdeKIP/symfony-coding-standard/commits/2.x-phpcs3-compatible) Everything seems to be working perfectly.

If it is decided to create a seperate branch feel free to fork mine back or create your own.

---

Thanks for all the help. Hope to see 3.0.0 release soon.

**Comment by wickedOne** [comment] 2017-06-14 19:46
yes, you're right: inbetween those commits we've changed the namespace of the sniffs and thus the rules in the ``ruleset.xml`` sorry for not catching that before making my comment yesterday...

your branch looks to be the v3 version of v2 of what i was trying to describe!

thanks for noticing!

and as you appear to be using the standard: if it's not too much time and effort for you, it would be highly appreciated if you're willing to run the current master branch of this repo against your codebase(s) and will let us know whether the new sniffs raise any false positives. so we can fix those.

as said earlier in this discussion: all of them are merely tested against the repositories i currently work with and djoos' so any input is welcomed!

**Comment by wickedOne** [comment] 2017-06-23 07:32
@djoos as #69, #68 and #66 are resolved i personally think #92 is the only thing standing in the way to create a v3 version and go forward from that.

do you have any release strategy for v3 or any additions for us to get to a v3?

p.s. feel free to contact me directly through email

**Comment by djoos** [comment] 2017-06-23 08:18
Hi @wickedOne,

after #92, I'm happy to go ahead and release v3. Thank you for the amazing work you put into the PHPCS3 migration!

I'll close this issue for now, however: give a yell if anyone has other objections to getting 3.0.0 out. Thanks in advance!

**Closed by djoos** 2017-06-23 08:18 UTC

**Comment by wickedOne** [comment] 2017-06-23 09:26
@djoos thanks & you're welcome: more than happy to give back to the community i pretty much based my carreer on... 😎 

i'll have a look @ #92 somewhere next week and guess we have to grab the false positives from each ci locked to ``dev-master`` :-)

**Comment by mnapoli** [comment] 2017-08-31 15:03
@djoos Hi, could you tag a 3.0 version?

Thanks!

**Comment by mnapoli** [comment] 2017-09-01 12:43
Awesome thanks!
